executor: slurm
jobs: 250
software-deployment-method:
   - conda
   - apptainer
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 8
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq
    # slurm_account: ${USER}
    mem_mb: attempt * 1024
    threads: 1
    runtime: attempt * 5
set-resources:
    build_snp_mapping_files:
      threads: *cores
      mem_mb: 22528 + attempt * 2048
      runtime: attempt * 60
    get_mirror_snps:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    filter_mirror_snps:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    filter_problematic_snps:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    compute_afreq:
      mem_mb: 20480 + attempt * 2048
      threads: *cores
    select_best_snps:
      mem_mb: 8192 + attempt * 1024
      threads: *cores
    filter_multiallelic_var:
      mem_mb: 20480 + attempt * 2048
      threads: *cores
    sanitize_problematic_snps:
      mem_mb: 1024 + attempt * 1024
      threads: 1
    recode_pgen:
        mem_mb: 102400 + attempt * 2048
        threads: *cores
    list_rs:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    header_info:
        mem_mb: 2048 + attempt * 2048
    select_samples:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    filter_var:
      mem_mb: 20480 + attempt * 2048
      threads: *cores
    filter_by_minimac3:
      mem_mb: 20480 + attempt * 2048
      threads: *cores
    create_bgen:
      mem_mb: 20480 + attempt * 2048
      threads: *cores
    qctool:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    get_hq_variants:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    filter_hq_variants:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    merge_filter_hq_variants:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    update_pgen_id:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    update_pgen_alleles:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    merge_qc_harmonised_pgen:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    pgen2bed:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    merge_qc_harmonised_bed:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    freq_qc_harmonised_pgen:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
