run:
  delivery: False

# paths
workspace_path: "results"
pgen_src_path: '/processing_data/shared_datasets/plasma_proteome/interval/genotypes/imputed/pgen/'
pgen_template: 'impute_dedup_{chrom}_interval.pgen'
pvar_template: 'impute_dedup_{chrom}_interval.pvar'
pgen_dest_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/pgen/'
fasta_path: '/exchange/healthds/public_data/reference_genomes/GRCh37/GCA_000001405.14_GRCh37.p13_full_analysis_set.fna'
fam_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/cleaned_genotype_INTERVAL.fam'
mapping_table: '/exchange/healthds/pQTL/results/INTERVAL/qced_sumstats/table.snp_mapping.tsv.gz'
pgen_template2: 'impute_recoded_selected_sample_filter_hq_var_{chrom}.pgen'

plink2_dict:
  mind: 0.1
  geno: 0.1
  hwe: 1e-15
  mac: 10
