run:
  delivery: True

# paths
workspace_path: "results"
pgen_src_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/HDS_by_chr'
pgen_template: 'chr{chrom}.pgen'
pvar_template: 'chr{chrom}.pvar'
dest_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/harmonized'
fam_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/BELIEVE_genotype_final_bed_123456_withoutPCoutliers_mac.fam'
mapping_table: '/exchange/healthds/pQTL/BELIEVE/harmonized_gwas/snp_mapping/table.snp_mapping_correct.tsv.gz'

plink2_dict:
  mind: 0.1
  geno: 0.1
  hwe: 1e-15
  mac: 10
  export_output_fmt: "bgen-1.1"
