run:
  delivery: False
  filter_problematic_snps: True
  filter_multiallelic_snps: True
  filter_by_imputation_quality: 'minimac3' # options: info_score, minimac3, none

# paths
workspace_path: "results"
pgen_src_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/HDS_BELIEVE_final_HDS_by_chr'
pgen_template: 'chr{chrom}.pgen'
pvar_template: 'chr{chrom}.pvar'
dest_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/harmonized'
problematic_snps_path: '/exchange/healthds/pQTL/BELIEVE/problematic_7k_snps/problematic_snps.txt'

## Sample selection - https://www.cog-genomics.org/plink/2.0/filter
sample_selection_method: 'keep-fam' # options: keep, keep-fam, remove, remove-fam
id_list_path: '/exchange/healthds/pQTL/BELIEVE/Genetic_QC_files/BELIEVE_genotype_final_bed_123456_withoutPCoutliers_mac.fam'

plink2_dict:
  mind: 0.1
  geno: 0.1
  hwe: 1e-15
  mac: 10
  export_output_fmt: "bgen-1.1"
  minimac3-r2-filter: 0.3

INFO_score: "0.7"
