# paths
workspace_path: "results"
pgen_src_path: '/processing_data/shared_datasets/plasma_proteome/interval/genotypes/imputed/pgen/'
pgen_template: "impute_dedup_{chrom}_interval.pgen"
pgen_dest_path: "/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/"
fasta_path: "/exchange/healthds/public_data/reference_genomes/GRCh37/GCA_000001405.14_GRCh37.p13_full_analysis_set.fna"
fam_path: "/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/cleaned_genotype_INTERVAL.fam"

plink2_dict:
	mind: 0.1
	geno: 0.1
	hwe: 1e-15
	mac: 10