run:
  delivery: False
  filter_problematic_snps: False
  filter_by_imputation_quality: "info_score" # options: info_score, minimac3, none

# paths
workspace_path: "results"
pgen_src_path: '/processing_data/shared_datasets/plasma_proteome/interval/genotypes/imputed/pgen/'
pgen_template: 'impute_dedup_{chrom}_interval.pgen'
pvar_template: 'impute_dedup_{chrom}_interval.pvar'
dest_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/'
problematic_snps_path: ''

## Sample selection - https://www.cog-genomics.org/plink/2.0/filter
sample_selection_method: 'keep-fam' # options: keep, keep-fam, remove, remove-fam
id_list_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/cleaned_genotype_INTERVAL.fam'

input_validation:
  autosomes_only: True
  max_missing_dosage_rate: 0.0

plink2_dict:
  mac: 10
  export_output_fmt: "bgen-1.2"
  minimac3-r2-filter: 0.3

INFO_score: "0.7"
