run:
  delivery: False

# paths
workspace_path: "results"
pgen_src_path: ''
pgen_template: 'chr{chrom}.pgen'
pvar_template: 'chr{chrom}.pvar'
dest_path: '/exchange/healthds/pQTL/'
fam_path: ''
mapping_table: ''

plink2_dict:
  mind: 0.1
  geno: 0.1
  hwe: 1e-15
  mac: 10
  export_output_fmt: "bgen-1.2"
