run:
  delivery: False

# paths
workspace_path: "results"
pgen_src_path: '/processing_data/shared_datasets/plasma_proteome/interval/genotypes/imputed/pgen/'
pgen_template: 'impute_dedup_{chrom}_interval.pgen'
pvar_template: 'impute_dedup_{chrom}_interval.pvar'
dest_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/'
fam_path: '/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/cleaned_genotype_INTERVAL.fam'
mapping_table: '/exchange/healthds/pQTL/results/INTERVAL/qced_sumstats/table.snp_mapping.tsv.gz'

plink2_dict:
  mind: 0.1
  geno: 0.1
  hwe: 1e-15
  mac: 10
